id: Qmbz4SjdSzJ3qgFUB4TktoxPQSHEb9NNNd4Q1LVY1gx9Po
description: ""
tags: []
trigger:
    type: https
    method: GET
    paths:
        - /verify
domains:
    - nftth
includes:
    - /functions/verify.go
execution:
    timeout: 20s
    memory: 20MB
    call: verify
